# Generated by Django 2.2.3 on 2022-06-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('mail', models.EmailField(max_length=254)),
                ('phoneno', models.IntegerField(max_length=10)),
                ('s1_date', models.DateField()),
                ('s1', models.CharField(max_length=255)),
                ('inter1_start', models.DateField()),
                ('inter1_end', models.DateField()),
                ('inter1', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('degree_Specialization', models.CharField(max_length=255)),
                ('degree_start', models.DateField()),
                ('degree_end', models.DateField()),
                ('linkedln', models.URLField()),
                ('github', models.URLField()),
                ('skills1', models.CharField(max_length=100)),
                ('skills2', models.CharField(max_length=100)),
                ('skills3', models.CharField(max_length=100)),
                ('skills4', models.CharField(max_length=100)),
                ('hobbies1', models.TextField(max_length=100)),
                ('hobbies2', models.TextField(max_length=100)),
                ('hobbies3', models.TextField(max_length=100)),
                ('hobbies4', models.TextField(max_length=100)),
                ('p1', models.TextField()),
                ('p2', models.TextField()),
                ('p3', models.TextField()),
                ('p1_startdate', models.DateField()),
                ('p1_enddate', models.DateField()),
                ('p2_startdate', models.DateField()),
                ('p2_enddate', models.DateField()),
                ('p3_startdate', models.DateField()),
                ('p3_enddate', models.DateField()),
                ('p1_desc', models.TextField()),
                ('p2_desc', models.TextField()),
                ('p3_desc', models.TextField()),
                ('i1', models.CharField(max_length=255)),
                ('i2', models.CharField(max_length=255)),
                ('i3', models.CharField(max_length=255)),
                ('i1_desc', models.TextField()),
                ('i2_desc', models.TextField()),
                ('i3_desc', models.TextField()),
                ('i1_startdate', models.DateField()),
                ('i1_enddate', models.DateField()),
                ('i2_startdate', models.DateField()),
                ('i2_enddate', models.DateField()),
                ('i3_startdate', models.DateField()),
                ('i3_enddate', models.DateField()),
                ('c1', models.CharField(max_length=255)),
                ('c2', models.CharField(max_length=255)),
                ('c3', models.CharField(max_length=255)),
                ('c1_desc', models.TextField()),
                ('c2_desc', models.TextField()),
                ('c3_desc', models.TextField()),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
