# Generated by Django 2.2.3 on 2022-06-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='degree_end',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='log',
            name='degree_start',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='log',
            name='i1_enddate',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='log',
            name='i1_startdate',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='log',
            name='i2_enddate',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='log',
            name='i2_startdate',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='log',
            name='i3_enddate',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='log',
            name='i3_startdate',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='log',
            name='inter1_end',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='log',
            name='inter1_start',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='log',
            name='p1_enddate',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='log',
            name='p1_startdate',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='log',
            name='p2_enddate',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='log',
            name='p2_startdate',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='log',
            name='p3_enddate',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='log',
            name='p3_startdate',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='log',
            name='s1_date',
            field=models.CharField(max_length=255),
        ),
    ]
